#logging:
#  level: debug
server:
  port: 8080
spring:
  mvc:
    view:
      prefix: view/
      suffix: .html
  datasource:
    url: jdbc:h2:mem:test;MVCC=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    name: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.MySQLDialect